config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'home#index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  #routing to provider authentication page
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  

  resources :users do
    resource :topics
    member do
      get 'dashboard' => 'users#dashboard', as: 'dashboard'
    end
  end
  
  resource :sessions

  resources :sources do
    collection do
      get 'refresh', to: 'sources#import_sources', as: 'refresh'
      get 'search', to: 'sources#search', as: 'search'
      get 'custom', to: 'sources#custom', as: 'custom'
    end
  end

  resources :countries

  resources :languages
  
  resources :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"],
      token: auth_hash["credentials"]["token"]
    )
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end

end

app/models/category.rb
class Category < ApplicationRecord

validates :category_name, uniqueness: true
validates :category_name, presence: true

end

app/models/country.rb
class Country < ApplicationRecord

  validates :country_code, uniqueness: true
  validates :country_code, presence: true
  validates :country_name, uniqueness: true
  validates :country_name, presence: true

end

app/models/language.rb
class Language < ApplicationRecord

  validates :language_code, uniqueness: true
  validates :language_code, presence: true
  validates :language_name, uniqueness: true
  validates :language_name, presence: true


end

app/models/source.rb
class Source < ApplicationRecord

  validates :code, uniqueness: true
  validates :code, presence: true

  scope :check_sources, -> (search_entry) { where("name ILIKE ?", "%#{search_entry}%") }

  #add language/country/category search if there's time

end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :authentications, dependent: :destroy
  has_one :topic
  has_secure_password

  validates :email, uniqueness: true
  validates :email, presence:true
  validates :name, presence: true

  def self.create_with_auth_and_hash(authentication, auth_hash)
   user = self.create!(
     name: auth_hash["info"]["name"],
     email: auth_hash["info"]["email"],
     password: 'google'
   )
   user.authentications << authentication
   return user
  end

   # grab google to access google for user data
   def google_token
     x = self.authentications.find_by(provider: 'google_oauth2')
     return x.token unless x.nil?
   end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authorize
  before_action :check_admin

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/sources_controller.rb
require 'news_api'

class SourcesController < ApplicationController
  before_action :authorize
  before_action :check_admin, except: [:search, :custom]


  def index
    @sources = Source.all
  end

  def search
    @sources = Source.all

    filter_params(params).each do |key,value|
      @sources = @sources.public_send(key,value) if value.present?
    end
  end

  def custom
    news = params[:news]
    api = NewsApi.new
    @custom_info = api.custom_source(params[:news])['articles']

    if @custom_info.nil?
      flash[:error] = "Connection Error. Please try again later"
    end

    respond_to do |format|
      format.js
    end

  end

  #button for manual run
  def import_sources
    #call api
    api = NewsApi.new
    api_info = api.get_sources['sources']
    api_source_codes = []

    if api_info.nil?
      flash[:error] = "Connection Error. Please try again later"
    else
    #update to db
      api_info.each_with_index do |source,i|
        news = api_info[i]
        
        api_source_codes << news["id"]

        if Source.find_by_code(code=news["id"]).nil?
          Source.create(code: news["id"], name: news["name"], description: news["description"], url: news["url"], category: news["category"], language: news["language"], country_code: news["country"])
        else
          source = Source.where("code='#{news["id"]}'")

          source.each_with_index do |s,i|
            s.update(code: news["id"], name: news["name"], description: news["description"], url: news["url"], category: news["category"], language: news["language"], country_code: news["country"])
          end
        end
      end

      #remove from db
      Source.all.each do |db|
        (db.destroy) if !api_source_codes.include?(db.code)
      end

      flash[:success] = "Updated"
      redirect_to admin_index_path
    end
  end

  def 

  #manually create sources -- add if theres time
  # def new
  # end

  # def create
  # end

  def destroy
    @source = Source.find(params[:id])
    @source.destroy

    flash[:success] = "Deleted"
    redirect_to sources_path

  end

  private 
  def filter_params(param)
    params.slice(:check_sources)
  end

  def source_params
    params.require(:source).permit(:code, :name, :description, :url, :category, :language, :country_code)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :find_user

  

  def new
    @topics = Topic.new
  end

  def create
    @topics = Topic.new(topic_params)
  end

  private

  def find_user
    @user = User.find_by_id(current_user.id)
  end

  def topic_params
    params[:topic].permit(languages:[], portals:[], categories:[], countries:[], keywords:[])
  end

end

app/controllers/users_controller.rb
require 'news_api'

class UsersController < ApplicationController

  before_action :authorize, only: [:dashboard, :show, :edit, :update]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Successfully signed up"
      redirect_to dashboard_user_path(current_user)
    else
      flash[:error] = "Failed to create"
      render "new"
    end

  end

  def dashboard
      @user = User.find(params[:id])

      #call default api
      api = NewsApi.new

      @api_default = api.default['articles']

      if api.default['articles'].nil?
        flash[:error] = "Site is currently not working. Please try again later"
        redirect_to dashboard_user_path(current_user)
      end

    end

private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end


end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sources/_searchoutput.html.erb
  <p>Results for <%=@custom_info[0]["source"]["name"]%></p>

  <div style="width: 100%; display:flex; flex-wrap: wrap; justify-content: center;">

  <% @custom_info.each do |a| %>
   <div class="card news-box" style=" margin: 3%">
          <% if !a["urlToImage"].nil? %>
            <%= image_tag a["urlToImage"], class:"card-img-top"%>
          <% else %>
            <%= image_tag 'http://www.volusia.com/wp-content/uploads/2013/07/news.jpg', class:"card-img-top"%>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= a['title']%></h5>
            <div class="card-text">
              <p>
                <%= a["source"]["name"] %> | <%= a["author"] %> | <%= a["publishedAt"].to_time %>
              </p>
              <p>
                <%= a["description"] %>
              </p>
            </div>
              <%= link_to "Read Full Article", "#{a['url']}", class:"btn btn-sm btn-primary", target: :_blank %>
          </div>
        </div>
    <% end %>
  </div>
  

app/views/sources/custom.js.erb
$('#search-results').empty().removeClass('fade-in').addClass('fade-in').append('<%= j render "sources/searchoutput" %>');

app/views/sources/index.html.erb
<p></p>
<br>

<p>List of all sources</p>

<p><%= link_to "Back", admin_index_path %></p>


<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Category</th>
      <th>Source Country</th>
      <th>Source Language</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @sources.order(:code).each do |s| %>
      <tr>
        <td> <%= s.code %> </td>
        <td> <%= s.name %> </td>
        <td> <%= s.category %> </td>
        <td> <%= s.country_code %> </td>
        <td> <%= s.language_code %> </td>
        <td> <%= link_to "Delete", source_path(s), method: :delete, class:"btn btn-sm btn-danger" %> </td>
      </tr>
    <% end %>

  </tbody>

</table>

app/views/sources/search.html.erb
<%= provide :js do %>

    <!-- initial search load -->
    <script>
        $(document).on('turbolinks:load', function () {
        });
        // $.ajax({
        //   url: "new.api.com/v2/"
        //   method: "get",
        //   data: "",
        //   success: function(){
        //     $("#form").innerHTML = "reloaded from news api"
        //   },
        //   error: function(){
        //     $(".flash-error").innerHTML = "error loading from api"
        //   }
        // })
        // }
    </script>

<% end %>


<% if @sources.empty? %>
  No results
<% else %>
<div style="display:flex; flex-wrap: wrap; justify-content: space-around;">
  <% @sources.each do |source| %>
    <p><%= link_to "#{source.name}", custom_sources_path(news: source.code),remote: :true, class:"btn btn-sm btn-primary" %></p>
  <% end %>
<% end %>
</div>
<hr>
<p></p>


<div class="container" id="search-results">
  <p> Pick your preferred source </p>
</div>

app/views/topics/new.html.erb
Preferences:

Languages:

app/views/users/dashboard.html.erb
<div class="container" id="news" style="width: 100%; display:flex; flex-wrap: wrap; justify-content: center;">
  <% if @user.topic.nil? %>
    <% @api_default.each do |a| %>
      <div class="card news-box" style="margin: 3%">
        <% if !a["urlToImage"].nil? %>
          <%= image_tag a["urlToImage"], class:"card-img-top"%>
        <% else %>
          <%= image_tag 'http://www.volusia.com/wp-content/uploads/2013/07/news.jpg', class:"card-img-top"%>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= a['title']%></h5>
          <div class="card-text">
            <p>
              <%= a["source"]["name"] %> | <%= a["author"] %> | <%= a["publishedAt"].to_time %>
            </p>
            <p>
              <%= a["description"] %>
            </p>
          </div>
            <%= link_to "Read Full Article", "#{a['url']}", class:"btn btn-sm btn-primary", target: :_blank %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/new.html.erb
New User Form Page

<%= form_for @user do |f| %>
  <p>
  <%= f.label :name %>
  <%= f.text_field :name, required: 'required' %>
  </p>

  <p>
  <%= f.label :email %>
  <%= f.text_field :email, type: 'email', required: 'required' %>
  </p>

  <p>
    <%= f.label :password %>
    <%=f.password_field :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Already have an account? Log In Now', login_path %>