config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'home#index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  #routing to provider authentication page
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  

  resources :users do
    resource :topics
    member do
      get 'dashboard' => 'users#dashboard', as: 'dashboard'
    end
  end
  
  resource :sessions

  resources :sources do
    collection do
      get 'refresh', to: 'sources#import_sources', as: 'refresh'
      get 'search', to: 'sources#search', as: 'search'
      get 'custom', to: 'sources#custom', as: 'custom'
    end
  end

  resources :countries

  resources :languages
  
  resources :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"],
      token: auth_hash["credentials"]["token"]
    )
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end

end

app/models/category.rb
class Category < ApplicationRecord

validates :category_name, uniqueness: true
validates :category_name, presence: true

end

app/models/country.rb
class Country < ApplicationRecord

  validates :country_code, uniqueness: true
  validates :country_code, presence: true
  validates :country_name, uniqueness: true
  validates :country_name, presence: true

end

app/models/language.rb
class Language < ApplicationRecord

  validates :language_code, uniqueness: true
  validates :language_code, presence: true
  validates :language_name, uniqueness: true
  validates :language_name, presence: true


end

app/models/source.rb
class Source < ApplicationRecord

  validates :code, uniqueness: true
  validates :code, presence: true

  scope :check_sources, -> (search_entry) { where("name ILIKE ?", "%#{search_entry}%") }

  #add language/country/category search if there's time

end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :authentications, dependent: :destroy
  has_one :topic
  has_secure_password

  validates :email, uniqueness: true
  validates :email, presence:true
  validates :name, presence: true

  def self.create_with_auth_and_hash(authentication, auth_hash)
   user = self.create!(
     name: auth_hash["info"]["name"],
     email: auth_hash["info"]["email"],
     password: 'google'
   )
   user.authentications << authentication
   return user
  end

   # grab google to access google for user data
   def google_token
     x = self.authentications.find_by(provider: 'google_oauth2')
     return x.token unless x.nil?
   end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authorize
  before_action :check_admin

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

<p>Admin Page</p>


<hr>
Manage News Options:

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Area</th>
      <th>Manage</th>
      <th>Refresh Sources</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Sources</td>
      <td><%= link_to 'View/Manage', sources_path, class:'btn btn-sm btn-info' %></td>
      <td><%= link_to 'Refresh Source Listing', refresh_sources_path, class:'btn btn-sm btn-warning' %></td>
    </tr>
    <tr>
      <td>Countries</td>
      <td><%= link_to 'View/Manage', countries_path, class:'btn btn-sm btn-info' %></td>
      <td></td>
    </tr>
    <tr>
      <td>Languages</td>
      <td><%= link_to 'View/Manage', languages_path, class:'btn btn-sm btn-info' %></td>
      <td></td>
    </tr>
      <tr>
      <td>Categories</td>
      <td><%= link_to 'View/Manage', categories_path, class:'btn btn-sm btn-info' %></td>
      <td></td>
    </tr>
  </tbody>

</table>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-light">
  <%= link_to 'HOME', root_path %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item" id="nav-item" style="margin-left: 1em">
        <% if current_user %>
          <% if !current_user.admin? %>
            <%= link_to 'DASHBOARD', dashboard_user_path(current_user) %>
          <% else %>
            <%= link_to 'ADMIN DASHBOARD', admin_index_path %>
          <% end %>
        <% end %>
      </li>
    </ul>

      <div class="login-area ml-sm-2 navbar-right">
      <% if current_user %>
        Hi
        <% if current_user.admin? %>
         Admin: 
         <% end %>
        <%= current_user.name %>
        <%= link_to 'Log Out', sessions_path("holder"), method: :delete %>
      <% else %>
        <%= link_to 'Sign Up', new_user_path %>
        <%= link_to 'Sign Up with Google', '/auth/google_oauth2' %>
        <%= link_to 'Log In', new_sessions_path %>
        <%= link_to 'Log In with Google', '/auth/google_oauth2' %>
    <% end %>
      </div>


  </div>
</nav>

<br>

<% if !current_user.nil? && !current_user.admin? %>
<div class="form-group" style="display:inline-flex;">
  <%= form_tag search_sources_path, id:"search", method: :get do %>
    <%= text_field_tag :check_sources,"", class:"col-10 form-control", placeholder:"Search Portals"%>
    <%= submit_tag "Search", class:"btn btn-sm btn-info"%>
<!--     <datalist id="list"></datalist> -->
  <% end %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsFlash</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tag %>
  
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <% flash.each do |key,value| %>
      <div class = "alert alert-<%= key %>"><%= value %></div>
    <% end %>

      <%= yield %>
  </body>
</html>